# Generated by Django 4.1 on 2022-08-27 11:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint', '0002_complaint_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together={('user', 'subject', 'complaint_status')},
        ),
    ]
